Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "sean-davis"
    google.google_client_email = "637198545853-compute@developer.gserviceaccount.com"
    google.google_json_key_location = "mine.json"
    google.name = "rstudio-server"
    google.image = "ubuntu-1604-xenial-v20161020"
    google.scopes = ['storage-full', 'bigquery', 'https://www.googleapis.com/auth/compute']

    override.ssh.username = ENV["GOOGLE_SSH_USER"]
    #override.ssh.private_key_path = "/Users/sdavis2/.ssh/id_rsa"
    override.ssh.private_key_path = ENV["GOOGLE_SSH_KEY_LOCATION"]
  end

end
